apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dmonitor-grafana-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore
  target:
    name: dmonitor-grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: dmonitor/oidc-client-secret
