apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dmonitor-podmonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: dmonitor
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
