apiVersion: v1
kind: Service
metadata:
  name: dmonitor-service
  namespace: default
  labels:
    app: dmonitor
spec:
  selector:
    app: dmonitor
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
