{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.createExternalSecret .Values.oidc.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-oidc-client-secret" (include "dmonitor.fullname" .)) .Values.oidc.clientSecret.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "dmonitor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ default (printf "%s-oidc-client-secret" (include "dmonitor.fullname" .)) .Values.oidc.clientSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.oidc.clientSecret.secretKey | default "client-secret" }}
      remoteRef:
        key: {{ printf "%s%s" .Values.externalSecrets.remoteKeyPrefix (default "oidc-client-secret" .Values.externalSecrets.remoteKey) }}
{{- end }}
