{{- if and .Values.oidc.enabled .Values.oidc.clientSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-oidc-client-secret" (include "dmonitor.fullname" .)) .Values.oidc.clientSecret.secretName }}
type: Opaque
stringData:
  {{ .Values.oidc.clientSecret.secretKey }}: |-
    {{ .Values.oidc.clientSecret.value | default "" }}
{{- end }}
