{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "dmonitor.fullname" . }}-pm
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "dmonitor.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: {{ .Values.metrics.port }}
      path: {{ .Values.metrics.path }}
      interval: 15s
{{- end }}
